import type { Metadata } from "next";
import "./globals.css";
import Banner from "@/components/banner";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Banner />
        <Navbar />
        {children}
        <div className="w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}
